### PR TITLE
Bug fix for adding multiple file access directories in one request

### PR DESCRIPTION
**Pull request by brucekirkpatrick**
Fix for issue: https://luceeserver.atlassian.net/projects/LDEV/issues/LDEV-2060

### CODE REVIEW

**Comment by michaeloffner** [comment]
@cfmitrah please add a ticket wioth test case for this and also link in this PR

**Comment by cfmitrah** [comment]
@michaeloffner  I've added a test case. **Pull request:** https://github.com/lucee/Lucee/pull/1042

**Comment by cfmitrah** [comment]
Hai @micstriit , I've faced an error like invalid access value [-1] while checking with updatedefaultsecuritymanager function. Could you please test with the below code. So, I've added a fix for this issue too. PR: **https://github.com/lucee/Lucee/pull/1043**

```
<cfscript>
    adm = new Administrator('server', "password");
    try{
        adm.updatedefaultsecuritymanager(
          file:"local"
        );
        writeoutput(fileread(expandpath('./testone/test.txt')));
    }
    catch(any e){
        writeDump(e.message);
    }
</cfscript>
```

**Comment by michaeloffner** [comment]
@cfmitrah can you please redirect this to 6.0

**Comment by michaeloffner** [comment]
@cfmitrah please give this a try

**Pull request merged**
