### PR TITLE
Additional logging in scheduled tasks

### PR DESCRIPTION
**Pull request by cubiclabs**
Additional logging was added to scheduled tasks while looking into problems detailed in this ticket:
https://luceeserver.atlassian.net/browse/LDEV-897

I thought that it might be useful going forward.

### CODE REVIEW

**Comment by yamikuronue** [comment]
Please merge this PR. It would have saved us days of frustration at my work if we had some way to see why tasks were silently failing while we were debugging them.

**Comment by isapir** [comment]
Is there a reason you used DateTimeImpl instead of the CFML functions like DateFormat() and DateDiff()?

**Comment by cubiclabs** [comment]
I just tried to copy what was already there. DateTimeImpl was already being used in log output so assumed that was the right thing to use.

My knowledge of Java is minimal.

**Comment by cubiclabs** [comment]
Is there anything else I need to do in order to get this accepted??

**Comment by isapir** [comment]
Sorry for the delay.  I will try to look at this today.

**Pull request merged**
