### PR TITLE
LDEV-573 - Updating text and links in the admin.

### PR DESCRIPTION
**Pull request by andrew-dixon**
Updating the text and links in the admin as described on ticket LDEV-573.

### CODE REVIEW

**Comment by andrew-dixon** [comment]
My editor appears to have stripped a lot of whitespace from the edited files which makes the diff very difficult to see the changes.

**Comment by modius** [comment]
Nice.

**Comment by bdw429s** [comment]
Just add `?w=1` to the end of the URL to ignore whitespace.

https://github.com/lucee/Lucee/pull/4/files?w=1

**Comment by andrew-dixon** [comment]
@bdw429s Good to know.

**Comment by michaeloffner** [comment]
Why moving away from issues.lucee.org, I have chosen this URL so we get independent of the bug tracker we use. It is not impossible that in the future the URL of the bug tracker changes, when we use issues.lucee.org we only can change the direct and every update still points to the right point.

**Comment by andrew-dixon** [comment]
Because the link doesn't work, but I think that is because it was https instead of http. I'll update it all later.

**Comment by andrew-dixon** [comment]
@michaeloffner I've updated the issue tracker links as requested.

**Pull request merged**
