### PR TITLE
LDEV-3711

### PR DESCRIPTION
**Pull request by bdw429s**
Preserve the cause in DatabaseExceptions which can contain valuable nested exceptions from the JDBC driver.

### CODE REVIEW

**Comment by bdw429s** [comment]
https://luceeserver.atlassian.net/browse/LDEV-3711

**Comment by michaeloffner** [comment]
this is wrong that way, in my opinion it should be
`initCause( sqle );`
the SQLException itself already is the cause, what you do is the cause of the cause. The SQL exception itself may has no cause.
But otherwise i agree with the PR a 100%

**Comment by bdw429s** [comment]
@micstriit Problem is I tried that originally and it did not work for some reason.  I had this code:
```js
if( sqle.getCause().getCause() != null ) {
  initCause( sqle.getCause().getCause() );
}
```
and the if statement was not entered for the MySQL example I discussed in the ticket.  When I removed the if and set the top cause, the correct behavior was observed in my tests resulting int he correct stack trace that I put in the ticket.  

So what you're saying makes sense, but it doesn't seem to be correct.  The code I sent in the pull is what actually worked in real life.

**Comment by bdw429s** [comment]
@micstriit I have updated the pull.

**Pull request merged**
