### PR TITLE
Fix spelling and grammar in Lucee admin

### PR DESCRIPTION
**Pull request by psarin**
First pass at fixing grammar, spelling, and commas. Also, reworded Single Mode / Multi Mode descriptions to be clearer.

### CODE REVIEW

**Comment by zspitzer** [comment]
@psarin looking good, would you be able to move those inline overview strings in to the .json file?

then @andreasRu can do the localisation for DE and ES using his translation tool https://github.com/andreasRu/lucee-admin-language-editor

**Comment by psarin** [comment]
Moved inline overview strings to json files & test file. Prefixed untranslated DE string with **. Also, additional grammar fixes that were missed the first time around.

I also have worked on moving the "pool" inline texts in overview.cfm. Will submit that pull request after this one is approved.

**Comment by andreasRu** [comment]
Great commit!!! Thx! Going to add German & Spanish asap.

**Comment by psarin** [comment]
Modified references to pool in overview.cfm. Moved strings to language files. 

Additional variables were being set, pointing to original variables (see below). Deleted these additional cfset's since these variables were not being used in this file (or in project).


```
<cfset pool["Eden Space"]=pool["Par Eden Space"]>
<cfset pool["PS Eden Space"]=pool["Par Eden Space"]>

<cfset pool["Survivor Space"]=pool["Par Survivor Space"]>
<cfset pool["PS Survivor Space"]=pool["Par Survivor Space"]>

<cfset pool["Perm Gen"]=pool["CMS Perm Gen"]>

<cfset pool["Tenured Gen"]=pool["CMS Old Gen"]>
<cfset pool["PS Old Gen"]=pool["CMS Old Gen"]>
```

**Comment by zspitzer** [comment]
@psarin looking good!

are you ready for this to be merged, or do you have other changes you want to make?

**Comment by psarin** [comment]
That’s it for now :)
    	Get Outlook for iOS
    
  

 From: Zac Spitzer ***@***.***>Sent: Tuesday, July 18, 2023 14:38To: lucee/Lucee ***@***.***>Cc: Cage ***@***.***>; Mention ***@***.***>Subject: Re: [lucee/Lucee] Fix spelling and grammar in Lucee admin (PR #2180) 
@psarin looking good!
are you ready for this to be merged, or do you have other changes you want to make?

**Comment by zspitzer** [comment]
thanks!

merged as 6.0.0.515

you might need to restart lucee if updating in place locally, there's a deployment bug in 6 atm

**Pull request merged**
