### PR TITLE
Typos in Lucee admin

### PR DESCRIPTION
**Pull request by murphydan**
Typos in Lucee admin.

### CODE REVIEW

**Comment by micstriit** [comment]
thanks a lot for your pull. Is it possible you can do the pull against the branch "5.0". "master" is not an active development branch, "master" only get the merge from the current stable release branch (atm "5.0") from time to time.

**Comment by murphydan** [comment]
I've changed the base to 5.0 (not 5.0.0 which also exists?) and now it looks like there are a couple of conflicting files. Not sure if I need to resolve those or if they'll get resolved when this gets merged? Thoughts @micstriit ?

**Comment by murphydan** [comment]
Also, does it make sense to change the readme to give pull request info? Or maybe it already exists somewhere and I didn't see it...

**Comment by bdw429s** [comment]
@murphydan That's a good idea.  We also need to add a `/CONTRIBUTING.md` file to our repo too with these sort of details.  
https://github.com/blog/1184-contributing-guidelines

**Comment by micstriit** [comment]
@bdw429s can you do the changes to the readme?

**Comment by micstriit** [comment]
as you can see here https://github.com/lucee/Lucee/pull/48/files the pull now includes changes unrelated to the goal of this pull, so the easiest way for me is to adapt your improvments manually and close that pull, if this is ok for you?

**Comment by micstriit** [comment]
i did adapt this pull requests input with this commit
https://github.com/lucee/Lucee/commit/9a738384406647ea6eab41a1147defd9cff31119
This this pull request is no longer needed, thanks a lot for this.

**Comment by bdw429s** [comment]
@micstriit I added a `contributing.md` file and a section to the `readme.md` on the `5.0` branch as requested.  Do you want to take care of merging  them where they need to go?
https://github.com/lucee/Lucee/commit/9aa1269192a2edc37b447497d2ffd684c7ec00a4
https://github.com/lucee/Lucee/commit/5170565d33b783190bae568d19aef153226151ab

**Pull request closed without merging**
