### PR TITLE
Added a testcase to check content-Type of cfcontent without type attribute for LDEV-3742

### PR DESCRIPTION
**Pull request by cfmitrah**
https://luceeserver.atlassian.net/browse/LDEV-3742

### CODE REVIEW

**Comment by zspitzer** [comment]
@cfmitrah you can't use cfhttp in test cases, there's no http server when running them with script-runner

**Comment by cfmitrah** [comment]
@zspitzer I disabled the testcase

**Comment by zspitzer** [comment]
why disabled? just use `_internalRequest` ?

**Comment by cfmitrah** [comment]
@zspitzer  _internalRequest() doesn't work with cfcontent like cfhttp. It doesn't return any result and abort the request at the location of _internalRequest().

I filed a bug for the issue https://luceeserver.atlassian.net/browse/LDEV-3761

**Pull request merged**
