### PR TITLE
Fixes LDEV-469 (cfhttp clientCert implementation)

### PR DESCRIPTION
**Pull request by jzuijlek**
https://github.com/lucee/Lucee/pull/1/files?w=1

### CODE REVIEW

**Comment by jzuijlek** [comment]
Again, "Failed to transfer file" error in Travis. Build test itself is fine.

**Comment by SimonHooker** [comment]
@jzuijlek this is due to the private variables that are set up relating to maven builds.  Travis does not expose private variables to remote pull requests for security reasons (as a malicious user could then expose them) 

@michaeloffner  is away at the moment but once he's back I'm sure he'll take a look at this :)

**Comment by jzuijlek** [comment]
Thanks @SimonHooker

**Comment by micstriit** [comment]
Thanks for this pull, we will need to change the file handling a little bit, the current implementation is limited to the local filesystem, lucee supports all virtual filesystems everywhere. in addition there is no check if the context has access on that file location.

**Comment by micstriit** [comment]
i merged the pull and did some changes to the file handling:
https://github.com/lucee/Lucee/commit/affb0dd1b9ac87473655a49d4c0fb007559025d5

**Comment by jzuijlek** [comment]
Thanks @micstriit

**Pull request merged**
