### PR TITLE
Added a fix for LDEV-27

### PR DESCRIPTION
**Pull request by cfmitrah**

### CODE REVIEW

**Comment by michaeloffner** [comment]
i disagree on this fix, please see my first comment in the ticket, general parsing only should be used when local is "US", if we change that, this could break a lot a existing code. Do you disagree ?

**Comment by cfmitrah** [comment]
@micstriit , We should consider the existing code too. So, OK for your intention of this issue. Is there any way to prevent the issue if any user faces this error?

**Comment by michaeloffner** [comment]
to be honest i would prefer to have that setting always on "false", ls* functions should not support this stupid unlogical collections of supported parsing masks, this should be limited to non "ls" date functions.
But for compatibility we do support it anyway.
Why you see the need for this?

**Comment by cfmitrah** [comment]
@michaeloffner, Just for my clarification only about the issue.

**Comment by michaeloffner** [comment]
@cfmitrah the underlying ticket for this is set to resolved. if that is still an issue that need to be addressed, please open a new ticket (that links LDEV-27) and create a new PR for Lucee 6.1

**Pull request closed without merging**
