### PR TITLE
CFMail splitting long HTML lines into multiple lines breaking the HTML [LDEV-4039]

### PR DESCRIPTION
**Pull request by dswitzer**
I've refactored CFMAIL to use `quoted-printable` content transfer encoding for all HTML parts. On the suggestion of @zspitzer, I added a system property/environment variable (i.e. `lucee.mail.use.7bit.transfer.encoding.for.html.parts`) which allows switching back to the old behavior. This defaults to `false` which changes the behavior, but the only downside I can see to switching to `quoted-printable` as the default encoding is the message size will be a little larger. However, it fixes issues like:

* **Line wrapping** — `quoted-printable` always wraps lines to 76 characters.
* **Does not break long strings** — Long strings are encoded in the line wrapping, which means you could have a string (like a link) longer than 1000 characters without CFMAIL breaking the string after 997 characters.
* **Encodes non-ASCII characters** — `quoted-printable` will encode characters you cannot normally send with 7bit encoding, such as 8bit UTF characters.

https://luceeserver.atlassian.net/browse/LDEV-4039

https://github.com/lucee/Lucee/pull/1706

### CODE REVIEW

**Comment by dswitzer** [comment]
FYI - The tests that are failing are not related to my pull request, but were broken in 5.3 when I forked the build.

**Comment by dswitzer** [comment]
I'm not sure why it's saying I haven't signed the CLA, I have and just did it again.

**Comment by zspitzer** [comment]
@dswitzer this PR is extremely messy with merges and all sort of stuff, that's why it's confused?

**Comment by dswitzer** [comment]
@zspitzer Any suggestions for resolving the issues?

**Comment by zspitzer** [comment]
the PR for 6.0 was clean, I'd suggest closing this one and copy the changes into a fresh fork off 5.3?

**Comment by dswitzer** [comment]
@zspitzer 

So I've tried creating a new branch from the Lucee 5.3 branch, I've tried rebasing, but I can't seem to clean my fork up. When I try create a new branch from the Lucee 5.3, when I try the pull request it wants to apply with it a bunch of other merges that are not mine. I seem to be running into the same issue outlined here:

https://stackoverflow.com/questions/6102297/how-do-i-clean-up-my-github-fork-so-i-can-make-clean-pull-requests

However, I've tried the recommend steps and it's making things worse. When I try `git pull --rebase upstream master` I start having to fix merge conflicts on tons of patches. Something just isn't right.

I don't use Git on a daily basis, so I'm sure I messed something up but I've been trying for hours now to fix it to no avail.

If you know how I can get a clean branch of 5.3, let me know. There's only 3 files that were changed and the changes were all very straightforward.

**Comment by dswitzer** [comment]
Okay, that took way too freaking much time, but it appears I finally was able to get a clean 5.3 branch to submit a pull request on:

https://github.com/lucee/Lucee/pull/1722

**Pull request closed without merging**
