### PR TITLE
LDEV-2332 add a feature switch to turn off thread.stop()

### PR DESCRIPTION
**Pull request by DominicWatson**
Allow systems to set a `-Dlucee.conf.disable.thread.stop=true` environment variable to stop Lucee from attempting to brute force stop threads. Effectively turning off request timeouts.

See https://luceeserver.atlassian.net/browse/LDEV-2332

### CODE REVIEW

**Comment by bdw429s** [comment]
@DominicWatson Would it be better to make this part of the request timeout setting?  Such as a value of 0 or -1?

**Comment by DominicWatson** [comment]
@bdw429s yes, and no. The issue with requestTimeout is that a developer can override it at any point in the request. You want a way for system administrators to disable the feature altogether.

Also, this prevents _any_ code from using Lucee's thread stopping code (which absolutely should be avoided).

Yes - there should be something better that allows you to specifically **disable** timeouts, and not just set them very high (setting them to zero in Lucee just has the effect of setting it really high). Ideally this should be configuration option (Admin + env vars, etc.).

But, right now the priority I think should be to prevent `thread.stop()` from happening at all. This is really a patch for the problem so that we can get stability back to our servers.

**Comment by michaeloffner** [comment]
please instead of this
System.getProperty("lucee.conf.allow.thread.stop", "true") == "true";
do this
Caster.toBooleanValue(SystemUtil.getSystemPropOrEnvVar("lucee.conf.allow.thread.stop", null), false);

**Comment by isapir** [comment]
I also don't like the name space of the property: `lucee.conf.allow.thread.stop`.

I think that it should be along the lines of `lucee.threads.stoppable` or `lucee.enable.thread.stop` or something else that is more consistent with the other properties that we already have.

**Comment by DominicWatson** [comment]
Cool, yes - I did a quick search any didn't find anything so went with that (I saw the `lucee.conf...` namespace somewhere in the docs).

I think perhaps, `lucee.enable.request.timeout.monitor` + some more succinct logic that completely disables the Controler from watching for request timeouts might be preferable. I think that is less obscure a concept than "stopping thread.stop() in Lucee".

**Comment by DominicWatson** [comment]
Going to close this and submit a new one when ready. This clearly isn't quite right.

**Pull request closed without merging**
